<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Version>1.0.22</Version>
		<Nullable>enable</Nullable>
		<Authors>Alexander Selishchev, Simon Mourier, William David Cossey, Benjamin Smith, Dag H. Baardsen, krmr, jddj007-hydra, shehrozeee, TheAtomicOption, ItWorksOnMyMachine, garryxiao</Authors>
		<PackageProjectUrl>https://github.com/etsoo/RazorEngineCore</PackageProjectUrl>
		<Description>NET10 Razor Template Engine</Description>
		<AssemblyVersion>1.0.1</AssemblyVersion>
		<FileVersion>1.0.1</FileVersion>
		<Company>ETSOO</Company>
		<PackageIcon>logo.png</PackageIcon>
		<PackageId>Etsoo.RazorEngineCore</PackageId>
		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>..\etsoo.snk</AssemblyOriginatorKeyFile>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<IsAotCompatible>false</IsAotCompatible>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<SatelliteResourceLanguages>en;zh-Hans;zh-Hant</SatelliteResourceLanguages>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>
	<ItemGroup>
	  <None Include="..\logo.png">
		<Pack>True</Pack>
		<PackagePath>\</PackagePath>
	  </None>
	  <None Include="build\Etsoo.RazorEngineCore.targets">
		<Pack>True</Pack>
		<PackagePath>build\;buildTransitive\</PackagePath>
	  </None>
	</ItemGroup>
	<ItemGroup>
		<None Include="$(OutputPath)\Microsoft.AspNetCore.Razor.Language.dll" Pack="true" PackagePath="lib/net10.0/" />
		<None Include="$(OutputPath)\RazorEngineCore.deps.json" Pack="true" PackagePath="lib/net10.0/" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Razor.Language" Version="6.0.36" />
		<PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.6.3" ExcludeAssets="runtime" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" ExcludeAssets="runtime" />
	</ItemGroup>
</Project>
